name: Fix Styling Issues

on: [pull_request]

permissions:
  contents: write

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Adjust the PHP version as needed
      - name: Install PHP-CS-Fixer
        run: composer global require friendsofphp/php-cs-fixer
      - name: Run PHP-CS-Fixer
        run: php $(composer global exec which php-cs-fixer) fix --config .php-cs-fixer.php
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling issues (PHP-CS-Fixer)
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
