name: Fix Styling Issues

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Install PHP-CS-Fixer
        run: |
          composer global require friendsofphp/php-cs-fixer
          echo "Adding Composer global bin directory to PATH"
          echo "PATH=%PATH%;%USERPROFILE%/.composer/vendor/bin" >> $env:PATH
      - name: Verify PHP-CS-Fixer Installation
        run: |
          where php-cs-fixer
      - name: Run PHP-CS-Fixer
        run: php php-cs-fixer fix --config .php-cs-fixer.php
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling issues (PHP-CS-Fixer)
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
